package POSTTEST_3;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NBC
 */
public class SIA extends javax.swing.JFrame {

    /**
     * Creates new form SyaratPosttest
     */
    public SIA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jk = new javax.swing.ButtonGroup();
        kwn = new javax.swing.ButtonGroup();
        Content = new javax.swing.JPanel();
        PHOME = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        PPROFIL = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        PVISI = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        PKTP = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        TFRT = new javax.swing.JTextField();
        TFRW = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        TFNama = new javax.swing.JTextField();
        TFTempat = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        TFTgl = new javax.swing.JTextField();
        RBLaki = new javax.swing.JRadioButton();
        RBPrp = new javax.swing.JRadioButton();
        TFKelurahan = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        TFKota = new javax.swing.JTextField();
        CBAgama = new javax.swing.JComboBox();
        CBStatus = new javax.swing.JComboBox();
        CBGol = new javax.swing.JComboBox();
        TFPekerjaan = new javax.swing.JTextField();
        RBWNA = new javax.swing.JRadioButton();
        RBWNI = new javax.swing.JRadioButton();
        TFAlamat = new javax.swing.JTextField();
        TFKecamatan = new javax.swing.JTextField();
        JBReset = new javax.swing.JButton();
        JBRegister = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        PATAS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PBAWAH = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PKANAN = new javax.swing.JPanel();
        PKIRI = new javax.swing.JPanel();
        BProfil = new javax.swing.JButton();
        BHome = new javax.swing.JButton();
        BKtp = new javax.swing.JButton();
        BInformasi = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        Content.setBackground(new java.awt.Color(255, 153, 153));
        Content.setLayout(new java.awt.CardLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\41274..jpg")); // NOI18N

        javax.swing.GroupLayout PHOMELayout = new javax.swing.GroupLayout(PHOME);
        PHOME.setLayout(PHOMELayout);
        PHOMELayout.setHorizontalGroup(
            PHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHOMELayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel11)
                .addContainerGap(130, Short.MAX_VALUE))
        );
        PHOMELayout.setVerticalGroup(
            PHOMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PHOMELayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        Content.add(PHOME, "card5");

        jLabel27.setText("Universitas Mulawarman di singkat unmul adalah Perguruan Tinggi Negeri Samarinda Kalimantan Timur Indonesia");

        jLabel28.setText("Universitas ini berdiri pada tanggal 27 September 1962, sehingga merupakan universitas tertua di Kalimantan Timur.");

        jLabel29.setText("Universitas Mulawarman merupakan perguruan tinggi dengan jumlah mahasiswa terbesar di Kalimantan,");

        jLabel30.setText("dengan jumlah mahasiswa mencapai lebih dari 37.000 orang.");

        jLabel31.setText("Kampus utamanya terletak di Gunung Kelua, sedangkan kampus lainnya terdapat di Jalan Pahlawan, Jalan Banggeris dan Jalan Flores.");

        javax.swing.GroupLayout PPROFILLayout = new javax.swing.GroupLayout(PPROFIL);
        PPROFIL.setLayout(PPROFILLayout);
        PPROFILLayout.setHorizontalGroup(
            PPROFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPROFILLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PPROFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        PPROFILLayout.setVerticalGroup(
            PPROFILLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PPROFILLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap(440, Short.MAX_VALUE))
        );

        Content.add(PPROFIL, "card2");

        jLabel8.setText("VISI DAN MISI");

        jLabel33.setText("VISI");

        jLabel34.setText("Universitas berstandar internasional yang mampu berperan dalam pembangunan bangsa melalui pendidikan, penelitian,");

        jLabel35.setText("dan pengabdian kepada masyarakat yang bertumpu pada sumber daya alam (sda) khususnya hutan tropis lembab");

        jLabel36.setText("(tropical rain forest) dan lingkungannya.");

        jLabel37.setText("MISI");

        jLabel38.setText("Menghasilkan sumber daya manusia yang berkualitas, berkepribadian dan profesional");

        jLabel39.setText("melalui penyelenggaraan pendidikan tinggi yang bertaraf Internasional.");

        javax.swing.GroupLayout PVISILayout = new javax.swing.GroupLayout(PVISI);
        PVISI.setLayout(PVISILayout);
        PVISILayout.setHorizontalGroup(
            PVISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVISILayout.createSequentialGroup()
                .addGroup(PVISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PVISILayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel8))
                    .addGroup(PVISILayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(PVISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(PVISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel33)
                                .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel34, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)
                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PVISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel39, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)))))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        PVISILayout.setVerticalGroup(
            PVISILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PVISILayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel8)
                .addGap(31, 31, 31)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel36)
                .addGap(29, 29, 29)
                .addComponent(jLabel37)
                .addGap(18, 18, 18)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        Content.add(PVISI, "card3");

        jPanel10.setBackground(new java.awt.Color(0, 204, 204));

        jLabel12.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel12.setText("Nama");

        jLabel13.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel13.setText("Alamat");

        jLabel14.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel14.setText("Tempat/Tanggal Lahir");

        jLabel15.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel15.setText("Jenis Kelamin");

        jLabel16.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel16.setText("RT/RW");

        jLabel9.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel9.setText("Kota");

        jLabel17.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel17.setText("Kel/Desa");

        jLabel18.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel18.setText("Kecamatan");

        jLabel19.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel19.setText("Agama");

        jLabel20.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel20.setText("Status");

        jLabel21.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel21.setText("Golongan Darah");

        jLabel22.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel22.setText("Pekerjaan");

        jLabel23.setFont(new java.awt.Font("Vani", 0, 14)); // NOI18N
        jLabel23.setText("Kewarganegaraan");

        TFNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNamaActionPerformed(evt);
            }
        });

        jLabel24.setText("/");

        jk.add(RBLaki);
        RBLaki.setText("Laki-laki");

        jk.add(RBPrp);
        RBPrp.setText("Perempuan");

        jLabel25.setText("/");

        CBAgama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen Protestan", "Katolik", "Hindu", "Budha" }));
        CBAgama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBAgamaMouseClicked(evt);
            }
        });

        CBStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kawin", "Tidak Kawin" }));

        CBGol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "O", "AB" }));

        kwn.add(RBWNA);
        RBWNA.setText("WNA");

        kwn.add(RBWNI);
        RBWNI.setText("WNI");

        JBReset.setBackground(new java.awt.Color(0, 153, 153));
        JBReset.setText("RESET");
        JBReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBResetActionPerformed(evt);
            }
        });

        JBRegister.setBackground(new java.awt.Color(0, 153, 153));
        JBRegister.setText("REGISTER");
        JBRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRegisterActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Vani", 1, 24)); // NOI18N
        jLabel26.setText("FORM KARTU TANDA PENDUDUK");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(jLabel26)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JBReset)
                                .addGap(18, 18, 18)
                                .addComponent(JBRegister))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                                            .addComponent(jLabel14)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                        .addGroup(jPanel10Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(113, 113, 113)))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel13))
                                        .addGap(63, 63, 63)))
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(RBLaki)
                                        .addGap(18, 18, 18)
                                        .addComponent(RBPrp))
                                    .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(TFTempat, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel10Layout.createSequentialGroup()
                                        .addComponent(TFRT, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(TFRW, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(TFKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFKota, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CBAgama, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TFPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CBGol, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(RBWNA)
                                .addGap(18, 18, 18)
                                .addComponent(RBWNI))))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel18)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel19))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel20))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel21)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(TFNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBRegister)
                            .addComponent(JBReset))
                        .addGap(31, 31, 31)))
                .addGap(3, 3, 3)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(TFTempat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(RBLaki)
                    .addComponent(RBPrp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TFAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TFRT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFRW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(TFKelurahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(TFKecamatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(TFKota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(CBAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(CBStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(CBGol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(TFPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(RBWNA)
                    .addComponent(RBWNI))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout PKTPLayout = new javax.swing.GroupLayout(PKTP);
        PKTP.setLayout(PKTPLayout);
        PKTPLayout.setHorizontalGroup(
            PKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PKTPLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PKTPLayout.setVerticalGroup(
            PKTPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PKTPLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Content.add(PKTP, "card4");

        getContentPane().add(Content, java.awt.BorderLayout.CENTER);

        PATAS.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("SISTEM INFORMASI AKADEMIK");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("PROGRAM STUDI TEKNIK INFORMATIKA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("UNIVERSITAS MULAWARMAN");

        javax.swing.GroupLayout PATASLayout = new javax.swing.GroupLayout(PATAS);
        PATAS.setLayout(PATASLayout);
        PATASLayout.setHorizontalGroup(
            PATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PATASLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(PATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap(574, Short.MAX_VALUE))
        );
        PATASLayout.setVerticalGroup(
            PATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PATASLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(PATASLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PATASLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        getContentPane().add(PATAS, java.awt.BorderLayout.PAGE_START);

        PBAWAH.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("MODUL PRAKTIKUM PEMROGRAMAN VISUAL JAVA");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Copyright@2015");

        javax.swing.GroupLayout PBAWAHLayout = new javax.swing.GroupLayout(PBAWAH);
        PBAWAH.setLayout(PBAWAHLayout);
        PBAWAHLayout.setHorizontalGroup(
            PBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PBAWAHLayout.createSequentialGroup()
                .addContainerGap(350, Short.MAX_VALUE)
                .addGroup(PBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBAWAHLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(296, 296, 296))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBAWAHLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(407, 407, 407))))
        );
        PBAWAHLayout.setVerticalGroup(
            PBAWAHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PBAWAHLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(38, 38, 38))
        );

        getContentPane().add(PBAWAH, java.awt.BorderLayout.PAGE_END);

        PKANAN.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout PKANANLayout = new javax.swing.GroupLayout(PKANAN);
        PKANAN.setLayout(PKANANLayout);
        PKANANLayout.setHorizontalGroup(
            PKANANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        PKANANLayout.setVerticalGroup(
            PKANANLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 563, Short.MAX_VALUE)
        );

        getContentPane().add(PKANAN, java.awt.BorderLayout.LINE_END);

        PKIRI.setBackground(new java.awt.Color(204, 204, 204));
        PKIRI.setLayout(new java.awt.GridBagLayout());

        BProfil.setText("PROFIL");
        BProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProfilActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 30);
        PKIRI.add(BProfil, gridBagConstraints);

        BHome.setText("HOME");
        BHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BHomeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 10, 0, 30);
        PKIRI.add(BHome, gridBagConstraints);

        BKtp.setText("FORM KTP");
        BKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BKtpActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 30);
        PKIRI.add(BKtp, gridBagConstraints);

        BInformasi.setText("INFORMASI");
        BInformasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInformasiActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 0, 30);
        PKIRI.add(BInformasi, gridBagConstraints);

        jButton2.setText("EXIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 34;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 10, 364, 30);
        PKIRI.add(jButton2, gridBagConstraints);

        getContentPane().add(PKIRI, java.awt.BorderLayout.LINE_START);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TFNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNamaActionPerformed

    private void CBAgamaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBAgamaMouseClicked
        // TODO add your handling code here:
        CBAgama.getSelectedItem();
    }//GEN-LAST:event_CBAgamaMouseClicked

    private void JBResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBResetActionPerformed
        // TODO add your handling code here:
        TFNama.setText("");
        TFAlamat.setText("");
        TFKecamatan.setText("");
        TFKelurahan.setText("");
        TFKota.setText("");
        TFTempat.setText("");
        TFTgl.setText("");
        TFPekerjaan.setText("");
        TFRT.setText("");
        TFRW.setText("");
        jk.clearSelection();
        kwn.clearSelection();
        CBAgama.setSelectedItem(null);
        CBGol.setSelectedItem(null);
        CBStatus.setSelectedItem(null);
    }//GEN-LAST:event_JBResetActionPerformed

    private void JBRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRegisterActionPerformed
        // TODO add your handling code here:
        String Agama, Gol, Status, jk = null, warga;
        String Nama = TFNama.getText();
        String Tempat = TFTempat.getText();
        String Tanggal = TFTgl.getText();
        String Alamat = TFAlamat.getText();
        String RT = TFRT.getText();
        String RW = TFRW.getText();
        String Kelurahan = TFKelurahan.getText();
        String Kecamatan = TFKecamatan.getText();
        String Kota = TFKota.getText();
        String Pekerjaan = TFPekerjaan.getText();
        Agama = CBAgama.getSelectedItem().toString();
        Gol = CBGol.getSelectedItem().toString();
        Status = CBStatus.getSelectedItem().toString();

        if (RBLaki.isSelected())
        jk = RBLaki.getText();
        else if (RBPrp.isSelected())
        jk = RBPrp.getText();

        if (RBWNA.isSelected())
        warga = RBWNA.getText();
        else if (RBWNI.isSelected())
        warga = RBWNI.getText();

        FormKTPOutput output = new FormKTPOutput (Nama,Alamat,Kecamatan,Kelurahan,Kota,Pekerjaan,RT,RW,Tempat,Tanggal,Agama,Gol,Status,jk);
        output.setVisible(true);
    }//GEN-LAST:event_JBRegisterActionPerformed

    private void BHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BHomeActionPerformed
        // TODO add your handling code here:
        PHOME.setVisible(true);     //mengatur PHOME bernilai benar, jadi PHOME yang akan ditampilkan
        PPROFIL.setVisible(false);  //mengatur PPROFIL bernilai salah, sehingga tidak ditampilkan, hanya yang bernilai benar yang akan ditampilkan
        PVISI.setVisible(false);
        PKTP.setVisible(false);
        
        
    }//GEN-LAST:event_BHomeActionPerformed

    private void BProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProfilActionPerformed
        // TODO add your handling code here:
        PHOME.setVisible(false);     
        PPROFIL.setVisible(true);  
        PVISI.setVisible(false);
        PKTP.setVisible(false);
        
    }//GEN-LAST:event_BProfilActionPerformed

    private void BInformasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInformasiActionPerformed
        // TODO add your handling code here:
        PHOME.setVisible(false);     
        PPROFIL.setVisible(false);
        PVISI.setVisible(true);
        PKTP.setVisible(false);
    }//GEN-LAST:event_BInformasiActionPerformed

    private void BKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BKtpActionPerformed
        // TODO add your handling code here:
        PHOME.setVisible(false);     
        PPROFIL.setVisible(false);
        PVISI.setVisible(false);
        PKTP.setVisible(true);
    }//GEN-LAST:event_BKtpActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SIA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SIA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BHome;
    private javax.swing.JButton BInformasi;
    private javax.swing.JButton BKtp;
    private javax.swing.JButton BProfil;
    private javax.swing.JComboBox CBAgama;
    private javax.swing.JComboBox CBGol;
    private javax.swing.JComboBox CBStatus;
    private javax.swing.JPanel Content;
    private javax.swing.JButton JBRegister;
    private javax.swing.JButton JBReset;
    private javax.swing.JPanel PATAS;
    private javax.swing.JPanel PBAWAH;
    private javax.swing.JPanel PHOME;
    private javax.swing.JPanel PKANAN;
    private javax.swing.JPanel PKIRI;
    private javax.swing.JPanel PKTP;
    private javax.swing.JPanel PPROFIL;
    private javax.swing.JPanel PVISI;
    private javax.swing.JRadioButton RBLaki;
    private javax.swing.JRadioButton RBPrp;
    private javax.swing.JRadioButton RBWNA;
    private javax.swing.JRadioButton RBWNI;
    private javax.swing.JTextField TFAlamat;
    private javax.swing.JTextField TFKecamatan;
    private javax.swing.JTextField TFKelurahan;
    private javax.swing.JTextField TFKota;
    private javax.swing.JTextField TFNama;
    private javax.swing.JTextField TFPekerjaan;
    private javax.swing.JTextField TFRT;
    private javax.swing.JTextField TFRW;
    private javax.swing.JTextField TFTempat;
    private javax.swing.JTextField TFTgl;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.ButtonGroup jk;
    private javax.swing.ButtonGroup kwn;
    // End of variables declaration//GEN-END:variables
}
